name: Hourly Workflow

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  awx-pr-to-draft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: sersoft-gmbh/setup-gh-cli-action@v2
        with:
          version: stable

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Create log
        run: touch log.txt

      - name: Run awx draft script
        run: python3 ./awxdraft.py > log.txt 2>&1
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.AWX_TOKEN }}

      - name: Review log
        run: cat log.txt
